portal:
  image: nginx
  ports:
   - "8080:80"
  volumes:
   - /home/docker/docker-cluster/cluster/default.conf:/etc/nginx/conf.d/default.conf
  links:
   - tomcat1:tomcat1
   - tomcat2:tomcat2
   - tomcat3:tomcat3
redis:
  image: redis
tomcat1:
  image: tomcat:7.0
  volumes:
   - /home/docker/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - /home/docker/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
   - /home/docker/docker-cluster/cluster/context.xml:/usr/local/tomcat/conf/context.xml
   - /home/docker/docker-cluster/cluster/lib/commons-pool2-2.2.jar:/usr/local/tomcat/lib/commons-pool2-2.2.jar
   - /home/docker/docker-cluster/cluster/lib/jedis-2.5.2.jar:/usr/local/tomcat/lib/jedis-2.5.2.jar
   - /home/docker/docker-cluster/cluster/lib/tomcat-redis-session-manager-2.0.0.jar:/usr/local/tomcat/lib/tomcat-redis-session-manager-2.0.0.jar
  links:
   - redis
tomcat2:
  image: tomcat:7.0
  volumes:
   - /home/docker/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - /home/docker/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
   - /home/docker/docker-cluster/cluster/context.xml:/usr/local/tomcat/conf/context.xml
   - /home/docker/docker-cluster/cluster/lib/commons-pool2-2.2.jar:/usr/local/tomcat/lib/commons-pool2-2.2.jar
   - /home/docker/docker-cluster/cluster/lib/jedis-2.5.2.jar:/usr/local/tomcat/lib/jedis-2.5.2.jar
   - /home/docker/docker-cluster/cluster/lib/tomcat-redis-session-manager-2.0.0.jar:/usr/local/tomcat/lib/tomcat-redis-session-manager-2.0.0.jar
  links:
   - redis
tomcat3:
  image: tomcat:7.0
  volumes:
   - /home/docker/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - /home/docker/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
   - /home/docker/docker-cluster/cluster/context.xml:/usr/local/tomcat/conf/context.xml
   - /home/docker/docker-cluster/cluster/lib/commons-pool2-2.2.jar:/usr/local/tomcat/lib/commons-pool2-2.2.jar
   - /home/docker/docker-cluster/cluster/lib/jedis-2.5.2.jar:/usr/local/tomcat/lib/jedis-2.5.2.jar
   - /home/docker/docker-cluster/cluster/lib/tomcat-redis-session-manager-2.0.0.jar:/usr/local/tomcat/lib/tomcat-redis-session-manager-2.0.0.jar
  links:
   - redis
