portal:
  image: nginx
  ports:
   - "8080:80"
  volumes:
   - /home/docker/docker-cluster/cluster/default.conf:/etc/nginx/conf.d/default.conf
  links:
   - tomcat1:tomcat1
   - tomcat2:tomcat2
   - tomcat3:tomcat3
tomcat1:
  image: tomcat
  volumes:
   - /home/docker/docker-cluster/cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - /home/docker/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - /home/docker/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
tomcat2:
  image: tomcat
  volumes:
   - /home/docker/docker-cluster/cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - /home/docker/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - /home/docker/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
tomcat3:
  image: tomcat
  volumes:
   - /home/docker/docker-cluster/cluster/server.xml:/usr/local/tomcat/conf/server.xml
   - /home/docker/docker-cluster/cluster/ROOT:/usr/local/tomcat/webapps/ROOT
   - /home/docker/docker-cluster/cluster/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml


